# Generated by Django 5.2.12 on 2026-04-07 04:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=30, unique=True, verbose_name='患者编号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('other', '其他')], max_length=10, verbose_name='性别')),
                ('age', models.PositiveIntegerField(verbose_name='年龄')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('group_name', models.CharField(blank=True, max_length=50, verbose_name='分组')),
                ('diagnosis', models.CharField(blank=True, max_length=100, verbose_name='诊断')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '患者',
                'verbose_name_plural': '患者',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_name', models.CharField(max_length=100, verbose_name='治疗方案')),
                ('start_date', models.DateField(verbose_name='治疗开始日期')),
                ('total_weeks', models.PositiveIntegerField(default=12, verbose_name='总随访周数')),
                ('followup_interval_days', models.PositiveIntegerField(default=14, verbose_name='随访间隔（天）')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='followup.patient', verbose_name='患者')),
            ],
            options={
                'verbose_name': '治疗',
                'verbose_name_plural': '治疗',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_number', models.PositiveIntegerField(verbose_name='第几次随访')),
                ('followup_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='随访日期')),
                ('symptoms', models.TextField(blank=True, verbose_name='症状变化')),
                ('medication_adherence', models.CharField(blank=True, max_length=100, verbose_name='用药依从性')),
                ('adverse_events', models.TextField(blank=True, verbose_name='不良反应')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='followup.treatment', verbose_name='治疗')),
            ],
            options={
                'verbose_name': '随访记录',
                'verbose_name_plural': '随访记录',
                'ordering': ['visit_number', 'followup_date'],
                'constraints': [models.UniqueConstraint(fields=('treatment', 'visit_number'), name='unique_followup_visit_number')],
            },
        ),
    ]
