# Generated by Django 5.2.12 on 2026-04-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='住址'),
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='出生日期'),
        ),
        migrations.AddField(
            model_name='patient',
            name='ethnicity',
            field=models.CharField(blank=True, max_length=30, verbose_name='民族'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='allergy_history',
            field=models.TextField(blank=True, verbose_name='过敏史'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='chief_complaint',
            field=models.TextField(blank=True, verbose_name='主诉'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='family_history',
            field=models.TextField(blank=True, verbose_name='家族史'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='group_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='分组'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='marital_history',
            field=models.TextField(blank=True, verbose_name='婚育史'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='past_history',
            field=models.TextField(blank=True, verbose_name='既往史'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='personal_history',
            field=models.TextField(blank=True, verbose_name='个人史'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='prescription',
            field=models.TextField(blank=True, verbose_name='处方'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='present_illness',
            field=models.TextField(blank=True, verbose_name='现病史'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='pulse_diagnosis',
            field=models.TextField(blank=True, verbose_name='脉诊'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='tcm_disease',
            field=models.CharField(blank=True, max_length=100, verbose_name='中医疾病'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='tongue_diagnosis',
            field=models.TextField(blank=True, verbose_name='舌诊'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='treatment_principle',
            field=models.TextField(blank=True, verbose_name='治则治法'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='western_disease',
            field=models.CharField(blank=True, max_length=100, verbose_name='西医疾病'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='患者编号'),
        ),
    ]
