# Generated by Django 5.2.12 on 2026-04-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0002_patient_address_patient_birth_date_patient_ethnicity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='planned_next_followup_date',
            field=models.DateField(blank=True, help_text='默认按本次随访后 14 天生成，可手动调整。', null=True, verbose_name='下次建议随访日期'),
        ),
    ]
