# Generated by Django 5.2.12 on 2026-04-07 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0003_followup_planned_next_followup_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treatment',
            options={'ordering': ['-start_date', '-created_at'], 'verbose_name': '诊疗', 'verbose_name_plural': '诊疗'},
        ),
        migrations.AddField(
            model_name='treatment',
            name='followup_closed',
            field=models.BooleanField(default=False, verbose_name='已结束回访'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='followup_closed_at',
            field=models.DateField(blank=True, null=True, verbose_name='结束回访日期'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='planned_next_followup_date',
            field=models.DateField(blank=True, help_text='默认按本次随访后 14 天生成，也可以手动调整。', null=True, verbose_name='下次建议随访日期'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='followup.treatment', verbose_name='诊疗'),
        ),
    ]
