# Generated by Django 5.2.12 on 2026-04-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='modify_window_days',
            field=models.PositiveIntegerField(blank=True, help_text='管理员默认 365 天，普通账号默认 3 天。', null=True, verbose_name='可修改/删除历史数据天数'),
        ),
    ]
